#!/bin/bash

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}
# Parameters: backtitle, title, text
display_menu(){
# Duplicate file descriptor 1 on descriptor 3
exec 3>&1
selection=$(dialog --backtitle $1 --title $2 --clear --cancel-label "Exit" \
    --menu $3 $HEIGHT $WIDTH 3 \
    "1" "Display System Information" \
    "2" "Display Disk Space" \
    "3" "Display Home Space Utilization" \
    2>&1 1>&3)

exit_status=$?
# Close file descriptor 3
exec 3>&-
}

display_radiolist(){
# Duplicate file descriptor 1 on descriptor 3
exec 3>&1
selection=$(dialog --backtitle $1 --title $2 --clear --cancel-label "Exit" \
    --radiolist $3 $HEIGHT $WIDTH 3 \
    "1" "Display System Information" "on" \
    "2" "Display Disk Space" "off" \
    "3" "Display Home Space Utilization" "off" \
    2>&1 1>&3)

exit_status=$?
# Close file descriptor 3
exec 3>&-
}

display_menu "BACKTITLE" "TITLE" "TEXT"
clear
echo "EXIT STATUS: " $exit_status
echo "SELECTED: " $selection
sleep 2
display_radiolist "BACKTITLE" "TITLE" "TEXT"
clear
echo "EXIT STATUS: " $exit_status
echo "SELECTED: " $selection
